// Generated by https://quicktype.io
class Cast{

  List<Actor> actors = new List();

  Cast.fromJsonMap(List<dynamic> json){
    if (json == null) return;

    json.forEach( (element){
      final newActor = Actor.fromJsonMap(element);
      actors.add((newActor));
    });
  }

  List get items => actors; 
}



class Actor {
  int castId;
  String character;
  String creditId;
  int gender;
  int id;
  String name;
  int order;
  String profilePath;

  Actor({
    this.castId,
    this.character,
    this.creditId,
    this.gender,
    this.id,
    this.name,
    this.order,
    this.profilePath,
  });

  Actor.fromJsonMap(Map<String, dynamic> json){
    castId = json['cast_id'];
    character = json['character'];
    creditId = json['credit_id'];
    gender = json['gender'];
    id = json['id'];
    name = json['name'];
    order = json['order'];
    profilePath = json['profile_path'];
  }

  getPosterImg(){
    
    if(profilePath == null){
      return 'https://thumbs.gfycat.com/KindTerrificIggypops-max-1mb.gif'; 
    } else {
      return 'https://image.tmdb.org/t/p/w500$profilePath';
    }
  }
}